### PR TITLE
Up version num

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@wolfv @lesteve this is ready to be merged

Once this is merged we can tackle the PRs in https://github.com/conda-forge/catkin_tools-feedstock/pulls

Any idea how to build this feedstock for Python 3.9?

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
weird why this wasn't picked up by the autotick bot...

**Comment by Tobias-Fischer** [comment]
The meta.yaml was in a subdirectory .. might be why.

**Comment by wolfv** [comment]
yes, that's exactly why :facepalm:

**Pull request merged**
